// utils/emailService.js

const sgMail = require('@sendgrid/mail');

// Set the API key from your environment variables
sgMail.setApiKey(process.env.SENDGRID_API_KEY);

const SENDER_EMAIL = process.env.SENDER_EMAIL;
const SUPPORT_TEAM_EMAIL = process.env.SUPPORT_TEAM_EMAIL;

/**
 * Sends an escalation email to the support team.
 * @param {object} details - The details for the escalation email.
 * @param {string} details.customerName - The name of the customer.
 * @param {string} details.customerEmail - The email of the customer.
 * @param {string} details.phoneNumber - The phone of customer
 * @param {string} [details.orderNumber] - The order number, if available.
 * @param {string} details.issueSummary - A summary of the customer's issue.
 * @returns {Promise<void>}
 */
async function sendEscalationEmail({ customerName, customerEmail, orderNumber, issueSummary }) {
  if (!SENDER_EMAIL || !SUPPORT_TEAM_EMAIL) {
    console.error("Sender or Support Team email is not configured in environment variables.");
    throw new Error("Email service is not configured.");
  }

  // Construct the subject line
  const subject = `Phone Escalation: ${customerName}${orderNumber ? ` - Order ${orderNumber}` : ''}`;
  
  // Construct the email body (using HTML for better formatting)
  const htmlBody = `
    <h2>Support Escalation Request</h2>
    <p>An AI agent has escalated a customer conversation that requires human attention.</p>
    <hr>
    <h3>Customer Details:</h3>
    <ul>
      <li><strong>Name:</strong> ${customerName || 'Not Provided'}</li>
      <li><strong>Email:</strong> ${customerEmail || 'Not Provided'}</li>
      <li><strong>Order Number:</strong> ${orderNumber || 'Not Provided'}</li>
      <li><strong>Phone Number:</strong> ${phoneNumber || 'Not Provided'}</li>
    </ul>
    <h3>Issue Summary:</h3>
    <p><em>This summary was generated by the AI based on the conversation:</em></p>
    <blockquote style="border-left: 4px solid #ccc; padding-left: 16px; margin: 0;">
      <p>${issueSummary}</p>
    </blockquote>
    <hr>
    <p>Please follow up with the customer via their email address to resolve this issue.</p>
  `;

  const msg = {
    to: SUPPORT_TEAM_EMAIL,
    from: SENDER_EMAIL,
    subject: subject,
    html: htmlBody,
  };

  try {
    await sgMail.send(msg);
    console.log(`Escalation email sent successfully for customer: ${customerName}`);
  } catch (error) {
    console.error("Error sending email via SendGrid:", error);
    if (error.response) {
      console.error(error.response.body);
    }
    // Re-throw the error to be handled by the calling endpoint
    throw new Error("Failed to send escalation email.");
  }
}

module.exports = {
  sendEscalationEmail,
};