// utils/emailService.js

const sgMail = require('@sendgrid/mail');

// Set the API key from your environment variables
sgMail.setApiKey(process.env.SENDGRID_API_KEY);

const SENDER_EMAIL = process.env.SENDER_EMAIL;
const SUPPORT_TEAM_EMAIL = process.env.SUPPORT_TEAM_EMAIL;

/**
 * Sends an escalation email to the support team.
 * @param {object} details - The details for the escalation email.
 * @param {string} details.customerName - The name of the customer.
 * @param {string} details.customerEmail - The email of the customer.
 * @param {string} details.phoneNumber - The phone of the customer.
 * @param {string} [details.orderNumber] - The order number, if available.
 * @param {string} details.issueSummary - A summary of the customer's issue.
 * @returns {Promise<void>}
 */
async function sendEscalationEmail({ customerName, customerEmail, orderNumber, phoneNumber, issueSummary }) {
  if (!SENDER_EMAIL || !SUPPORT_TEAM_EMAIL) {
    console.error("Sender or Support Team email is not configured in environment variables.");
    throw new Error("Email service is not configured.");
  }

  const subject = `Phone Escalation: ${customerName}${orderNumber ? ` - Order ${orderNumber}` : ''}`;
  
  const htmlBody = `
    <h2>Support Escalation Request</h2>
    <p>An AI agent has escalated a customer conversation that requires human attention.</p>
    <hr>
    <h3>Customer Details:</h3>
    <ul>
      <li><strong>Name:</strong> ${customerName || 'Not Provided'}</li>
      <li><strong>Email:</strong> ${customerEmail || 'Not Provided'}</li>
      <li><strong>Phone Number:</strong> ${phoneNumber || 'Not Provided'}</li>
      <li><strong>Order Number:</strong> ${orderNumber || 'Not Provided'}</li>
    </ul>
    <h3>Issue Summary:</h3>
    <p><em>This summary was generated by the AI based on the conversation:</em></p>
    <blockquote style="border-left: 4px solid #ccc; padding-left: 16px; margin: 0;">
      <p>${issueSummary}</p>
    </blockquote>
    <hr>
    <p>Please follow up with the customer via their email address to resolve this issue.</p>
  `;

  const msg = {
    to: SUPPORT_TEAM_EMAIL,
    from: SENDER_EMAIL,
    subject: subject,
    html: htmlBody,
  };

  try {
    await sgMail.send(msg);
    console.log(`Escalation email sent successfully for customer: ${customerName}`);
  } catch (error) {
    console.error("Error sending email via SendGrid:", error);
    if (error.response) {
      console.error(error.response.body);
    }
    throw new Error("Failed to send escalation email.");
  }
}

/**
 * Sends an address change request email to the support team.
 * @param {object} details - The details for the address change request email.
 * // --- MODIFIED: Added oldAddressDetails parameter ---
 * @param {string} details.oldAddressDetails - The old shipping address on file.
 * @param {string} details.newAddressDetails - The new address provided by the customer.
 * @returns {Promise<void>}
 */
// --- MODIFIED: Added oldAddressDetails to the function signature ---
async function sendAddressChangeRequestEmail({ customerName, customerEmail, phoneNumber, orderNumber, oldAddressDetails, newAddressDetails }) {
  if (!SENDER_EMAIL || !SUPPORT_TEAM_EMAIL) {
    console.error("Sender or Support Team email is not configured in environment variables.");
    throw new Error("Email service is not configured.");
  }

  const subject = `Urgent: Address Change Request for Order ${orderNumber}`;
  
  const htmlBody = `
    <h2>Customer Address Change Request</h2>
    <p>A customer has requested an address change for an existing order via the AI phone agent. Please review and take action immediately.</p>
    <hr>
    <h3>Order & Customer Details:</h3>
    <ul>
      <li><strong>Order Number:</strong> ${orderNumber}</li>
      <li><strong>Customer Name:</strong> ${customerName || 'Not Provided'}</li>
      <li><strong>Customer Email:</strong> ${customerEmail || 'Not Provided'}</li>
      <li><strong>Customer Phone:</strong> ${phoneNumber || 'Not Provided'}</li>
    </ul>

    <h3>Previous Shipping Address on File:</h3>
    <blockquote style="border-left: 4px solid #f0ad4e; padding-left: 16px; margin: 0; color: #555;">
      <p>${oldAddressDetails ? oldAddressDetails.replace(/\n/g, '<br>') : 'Not available'}</p>
    </blockquote>

    <h3>New Shipping Address Requested:</h3>
    <blockquote style="border-left: 4px solid #5cb85c; padding-left: 16px; margin: 0;">
      <p>${newAddressDetails.replace(/\n/g, '<br>')}</p>
    </blockquote>
    <hr>
    <p><strong>Action Required:</strong> Please manually update the shipping address for this order in Shopify and confirm with the customer.</p>
  `;

  const msg = {
    to: SUPPORT_TEAM_EMAIL,
    from: SENDER_EMAIL,
    subject: subject,
    html: htmlBody,
  };

  try {
    await sgMail.send(msg);
    console.log(`Address change request email sent for order: ${orderNumber}`);
  } catch (error) {
    console.error("Error sending address change email via SendGrid:", error);
    if (error.response) {
      console.error(error.response.body);
    }
    throw new Error("Failed to send address change request email.");
  }
}


module.exports = {
  sendEscalationEmail,
  sendAddressChangeRequestEmail, 
};